# Generated by Django 3.2 on 2021-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(db_index=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('material_type', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('license', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('cultivation_tax', models.IntegerField(blank=True, null=True)),
                ('amount_history', models.JSONField()),
                ('slug', models.CharField(max_length=15)),
                ('sequence', models.IntegerField()),
                ('creation_run', models.IntegerField(blank=True, null=True)),
                ('strain', models.IntegerField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_fields', models.JSONField()),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('kind', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
