# Generated by Django 3.2 on 2021-04-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdata',
            name='amount_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialdata',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
