# Generated by Django 3.2 on 2021-04-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210430_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticMaterialMeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.IntegerField(db_index=True, unique=True)),
                ('measure_type', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.IntegerField(db_index=True, unique=True)),
                ('material_name', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
