# Generated by Django 3.2 on 2021-04-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_statisticmaterialmeasureunit_statisticmaterialtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticmaterialmeasureunit',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
